#!/bin/sh
set -e

chmod -R 0700 /home/www/.ssh

eval `ssh-agent -s`

folders=$(find /home/www/.ssh -type d)
for folder in $folders; do
    if [ -d "$folder" ]; then
        chmod -R 0700 "$folder"
    fi
done

files=$(find /home/www/.ssh -type f)
for file in $files; do
    if [ -f "$file" ]; then
        chmod 0600 "$file"
    fi
done

pems=$(find /home/www/.ssh -type f -name "*.pem")
for file in $pems; do
    if [ -f "$file" ]; then
        ssh-add "$file"
    fi
done

pubs=$(find /home/www/.ssh -type f -name "*.pub")
for file in $pubs; do
    if [ -f "$file" ]; then
        chmod 0644 "$file"
    fi
done

exec "$@"
