#!/bin/bash
set -e

# Update nginx config
if [[ "${NGINX_CONFIG}" != '' ]]; then
    mapfile -t NGINX_CONFIG < <(echo "${NGINX_CONFIG}" | tr ',' "\n")
    nginx-config "${NGINX_CONFIG[@]}"
fi

for command in "$@"
do
    command=${command//' \ '/' '}
    $command
done

nginx -t

nginx -g "daemon off;"