#!/bin/bash
set -e

if [ -n "${MODULE_ENABLE}" ]; then
    php-enable "${MODULE_ENABLE}"
fi

if [ -n "${MODULE_DISABLE}" ]; then
    php-disable "${MODULE_DISABLE}"
fi

if [ -n "${PHP_CONFIG}" ]; then
	pconfig "${PHP_CONFIG}"
fi

if [ -n "${FPM_POOL}" ]; then
	ppool "${FPM_POOL}"
fi

exec "$@"