#!/bin/bash
set -e

if [ -n "${MODULE_ENABLE}" ]; then
    php-enable "${MODULE_ENABLE}"
fi

if [ -n "${MODULE_DISABLE}" ]; then
    php-disable "${MODULE_DISABLE}"
fi

if [ -n "${PHP_CONFIG}" ]; then
	php-config "${PHP_CONFIG}"
fi

if [ -n "${FPM_POOL}" ]; then
	php-pool "${FPM_POOL}"
fi

if [ -n "${MAILHOG_ADDR}" ]; then
	sed -i -E "s/--smtp-addr=[^ ]+/--smtp-addr=${MAILHOG_ADDR}\"/g" /usr/local/etc/php/conf.d/z-mail.ini
fi

if [ -n "${MAGERUN_VERSION}" ]; then
	download-magerun "${MAGERUN_VERSION}" &2> /dev/null
fi

exec "$@"